# Generated by Django 3.0.2 on 2020-01-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='me', max_length=20)),
                ('dest', models.CharField(default='home', max_length=100)),
                ('arrival', models.CharField(default='20', max_length=20)),
                ('pnum', models.IntegerField(default='1')),
                ('vtype', models.CharField(default='Sedan', max_length=20)),
                ('child', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('isOpen', models.BooleanField(default=False)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('isCompleted', models.BooleanField(default=False)),
                ('driver_id', models.IntegerField(default='0')),
                ('passenger_id', models.IntegerField(default='0')),
            ],
        ),
    ]
