# Generated by Django 3.0.2 on 2020-01-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='passenger_id',
        ),
        migrations.AlterField(
            model_name='ride',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
