# Generated by Django 3.0.2 on 2020-01-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20200126_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival',
            field=models.CharField(default='5:00pm-6:00pm', max_length=50),
        ),
    ]
