# Generated by Django 3.0.2 on 2020-01-27 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride', '0004_auto_20200127_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='you', max_length=20)),
                ('dest', models.CharField(default='bar', max_length=100)),
                ('arrival', models.CharField(default='5:00pm-6:00pm', max_length=50)),
                ('pnum', models.IntegerField(default='1')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
