# Generated by Django 3.0.2 on 2020-02-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_sharedride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(default='me', max_length=200),
        ),
        migrations.AlterField(
            model_name='sharedride',
            name='name',
            field=models.CharField(default='you', max_length=200),
        ),
    ]
