# Generated by Django 3.0.2 on 2020-02-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_auto_20200207_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(default='abc@gmail.com', max_length=200),
        ),
    ]
