# Generated by Django 3.0.2 on 2020-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0007_auto_20200207_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedride',
            name='name',
            field=models.CharField(default='def@gmail.com', max_length=200),
        ),
    ]
