# Generated by Django 3.0.2 on 2020-01-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200127_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isdriver',
            field=models.BooleanField(default=0),
        ),
    ]
